version: "3"
services:
  postgres-order:
    container_name: postgres-order
    image: postgres
    environment:
      POSTGRES_DB: DB_USER
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      PGDATA: /data/postgres

    volumes:
      - ./postgres-order:/data/postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    command: -p 5432
    restart: unless-stopped
  registry:
    build:
      context: ./REGISTRY-SERVICES
    ports:
      - "8761:8761"
  api-gateway:
    build:
      context: ./APIGATEWAY-SERVICES
    ports:
      - "9191:9191"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry:8761/eureka/
      # EUREKA_SERVER_ADDRESS=http://registry:8761/eureka/
    depends_on:
      - registry
  user-service:
    build:
      context: ./USER-SERVICES
    ports:
      - "8181:8181"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry:8761/eureka/
    depends_on:
      - registry
  customer-service:
    build:
      context: ./CUSTOMER-SERVICES
    ports:
      - "8182:8182"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry:8761/eureka/
    depends_on:
      - registry
  account-service:
    build:
      context: ./ACCOUNT-SERVICES
    ports:
      - "8183:8183"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry:8761/eureka/
    depends_on:
      - registry